import React from 'react';
import Head from 'next/head';
import './globals.css';
import Sidebar from './components/Sidebar';
import Header from './components/Header';
import Footer from './components/Footer'

export const metadata = {
  title: 'Agent ML',
  description: 'Generated by create next app',
}

export default function Layout({ children }) {
  return (
    <>
      <Head>
        {/* Include any necessary meta tags, title, or other head elements */}
        <title>Agent ML</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Sidebar />
        <div>
          <Header />
          <main>{children}</main>
        </div>
        <Footer />
      </div>
    </>
  );
};